# Generated by Django 2.0.6 on 2018-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image1', models.ImageField(upload_to='')),
                ('carousel_image2', models.ImageField(upload_to='')),
                ('carousel_image3', models.ImageField(upload_to='')),
                ('welcome_header', models.CharField(max_length=50)),
                ('welcome_text', models.TextField(max_length=1500)),
                ('supply_header', models.CharField(max_length=50)),
                ('supply_text', models.TextField(max_length=1500)),
                ('our_service_header', models.CharField(max_length=50)),
                ('our_service_text', models.TextField(max_length=1500)),
            ],
        ),
    ]
